Feat/verska home page
A-rtemFedorov/restoran pull request #2
Opened 2022-12-21 13:43 UTC by A-rtemFedorov

2022-12-21 13:54 UTC, KuzmaMutze commented
комити называй норм по стандартам

2022-12-21 14:08 UTC, KuzmaMutze commented
чо у тебя со шрифтами, визуальная часть отличается от макета

2022-12-21 14:10 UTC, KuzmaMutze commented
не пиксель перфект, текст прилипает к границам блоков
перепроверяй каждую делать

2022-12-21 14:16 UTC, KuzmaMutze commented
где картинка 
где слайдер с заказами и посетителями
![image](https://user-images.githubusercontent.com/54819013/208925459-20d95c4a-5979-4cf6-98ee-1a3974d8260b.png)
![image](https://user-images.githubusercontent.com/54819013/208925607-3836bb1c-4d9d-4e33-bd2f-80cc8fd8e47f.png)
![image](https://user-images.githubusercontent.com/54819013/208925927-b79fa145-be24-4522-9d96-1a69e8f3ab47.png)

2022-12-21 14:19 UTC, KuzmaMutze commented
чо с названиями?
![image](https://user-images.githubusercontent.com/54819013/208926714-b75adbed-0400-408b-ac3b-c8cf30224142.png)

2022-12-21 14:59 UTC, KuzmaMutze requested changes

2022-12-21 14:59 UTC, KuzmaMutze commented on package.json
> +    "browser-sync": "^2.27.10",
где еще? удаляй с компа
```
 "gulp": "^4.0.2",
 "gulp-imagemin": "7.1.0",
 "gulp-rename": "^2.0.0",
 "gulp-sass": "^5.1.0"
```

2022-12-21 14:59 UTC, KuzmaMutze commented on src/index.html
> +                    <img src="logo/LOGO.svg" alt="logo">
без капса

2022-12-21 14:59 UTC, KuzmaMutze commented on src/index.html
> +    <title>restoran</title>
с большой буквы и найди .ico какую нибудь чтобы красиво было

2022-12-21 14:59 UTC, KuzmaMutze commented on src/index.html
> +    <title>restoran</title>
в инете найди способ как вставить

2022-12-21 14:59 UTC, KuzmaMutze commented on src/index.html
> +                    <a href="#" class="header__nav-menu">главная</a>
.header__nav-link
nav это и есть menu

2022-12-21 14:59 UTC, KuzmaMutze commented on src/index.html
> +                        <div class="cards__title">Магическая <span class="cards__subtitle">Атмосфера</span></div>
span с новой строчки

2022-12-21 14:59 UTC, KuzmaMutze commented on src/index.html
> +                        <div class="cards__title">Лучшее качество <span class="cards__subtitle">Еды</span></div>
тут тож

2022-12-21 14:59 UTC, KuzmaMutze commented on src/index.html
> +                            <div class="history__title">Наша<span class="history__subtitle"> История</span></div>
тут тож

2022-12-21 14:59 UTC, KuzmaMutze commented on src/index.html
> +                            <div class="history__descr">Как и у любого другого самобытного места, у нас есть своя, особая история. Идея ресторана пришла основателям неожиданно. Во время прогулки по л
жесть чо с текстом, не красиво
тут тоже

2022-12-21 14:59 UTC, KuzmaMutze commented on src/index.html
> +                    <div class="booking__title">Отпразднуйте в одном из<br>
с новой строчки

2022-12-21 14:59 UTC, KuzmaMutze commented on src/index.html
> +            <div class="comments__text">Я надолго запомню мой День рождения, проведённый в этом ресторане! Кусочек родной Армении!!! Отдельное спасибо за комплепент в виде фруктовой тарелки. Будем ре
с новой

2022-12-21 14:59 UTC, KuzmaMutze commented on src/sass/blocks/_booking.scss
> +        font-weight: 400;
не нужно
400 браузер по дефолту задает

2022-12-21 14:59 UTC, KuzmaMutze commented on src/sass/blocks/_button.scss
> +    height: 47px;
убрать сделать падинги

2022-12-21 14:59 UTC, KuzmaMutze commented on src/sass/blocks/_button.scss
> +        color: black;
где sass переменные?

2022-12-21 14:59 UTC, KuzmaMutze commented on src/sass/blocks/_button.scss
> +    color: #FFFFFF;
в sass переменные

2022-12-21 14:59 UTC, KuzmaMutze commented on src/sass/blocks/_button.scss
> +
чо за пробел

2022-12-21 14:59 UTC, KuzmaMutze commented on src/sass/blocks/_button.scss
> +        background: #D67E34;
в переменную и bg-color

2022-12-21 14:59 UTC, KuzmaMutze commented on src/sass/blocks/_comments.scss
> +    background: #E6E5E5;
все цвета в переменную

2022-12-21 14:59 UTC, KuzmaMutze commented on src/sass/blocks/_comments.scss
> +        font-weight: 400;
400 везде удаляешь

2022-12-21 14:59 UTC, KuzmaMutze commented on src/sass/blocks/_comments.scss
> +        line-height: 27px;
зачем для однострочного текста `line-height`?
убирай везде `line-height` где одна строка или не текст

2022-12-21 14:59 UTC, KuzmaMutze commented on src/sass/blocks/_comments.scss
> +        font-weight: 400;
удалить

2022-12-21 14:59 UTC, KuzmaMutze commented on src/sass/blocks/_cooks.scss
> +        font-weight: 400;
del

2022-12-21 14:59 UTC, KuzmaMutze commented on src/sass/blocks/_description.scss
> +    height: 991;
991 чего?

2022-12-21 14:59 UTC, KuzmaMutze commented on src/sass/blocks/_description.scss
> +            box-shadow: #797878;
эт чо

2022-12-21 14:59 UTC, KuzmaMutze commented on src/sass/blocks/_description.scss
> +            font-weight: 400;
del

2022-12-21 14:59 UTC, KuzmaMutze commented on src/sass/blocks/_description.scss
> +            font-weight: 400;
по дефолту у браузера это тоже стоит
del

2022-12-21 14:59 UTC, KuzmaMutze commented on src/sass/blocks/_description.scss
> +                min-height: 217px;
почему `min-height`?

2022-12-21 14:59 UTC, KuzmaMutze commented on src/sass/blocks/_dishes.scss
> +
del

2022-12-21 14:59 UTC, KuzmaMutze commented on src/sass/blocks/_dishes.scss
> +
probel

2022-12-21 14:59 UTC, KuzmaMutze commented on src/sass/blocks/_dishes.scss
> +            transform: rotate(0.14deg);
ты это с фигмы скопировал?
сделай высоту побольше либо падинг

2022-12-21 14:59 UTC, KuzmaMutze commented on src/sass/blocks/_header.scss
> +
пробелы убераем

2022-12-21 14:59 UTC, KuzmaMutze commented on src/sass/blocks/_header.scss
> +        &:after {
зачем здесь after?

2022-12-21 14:59 UTC, KuzmaMutze commented on src/sass/libs/_font.scss
> +    font-family: 'Tinos', serif;;
зачем тебе папка fonts если ты от гугла подключаешь шрифты

2022-12-21 14:59 UTC, KuzmaMutze commented on src/sass/style.scss
> +}
в отдельный блок

2022-12-21 14:59 UTC, KuzmaMutze commented on src/sass/style.scss
> +@import 'libs/bootstrap.min';
зачем тебе бутстрап если ничего из него не используешь?

2022-12-21 18:20 UTC, A-rtemFedorov commented on src/sass/blocks/_header.scss
> +        &:after {
для линии чтобы в html ее не создавать

2022-12-21 18:20 UTC, A-rtemFedorov commented on src/sass/style.scss
> +@import 'libs/bootstrap.min';
контейнеры же из него идут

2022-12-21 18:31 UTC, A-rtemFedorov commented on src/index.html
> +                    <a href="#" class="header__nav-menu">главная</a>
это я разбирался с вложенностью про что я говорил

2022-12-22 21:58 UTC, KuzmaMutze requested changes

2022-12-22 21:58 UTC, KuzmaMutze commented on src/sass/blocks/_comments.scss
> +    background: #E6E5E5;
где переменные sass?

2022-12-22 21:58 UTC, KuzmaMutze commented on src/sass/blocks/_description.scss
> +            color: #BC9060;
переменные сас

2022-12-22 21:58 UTC, KuzmaMutze commented on gulpfile.js
> +});
зачем?

2022-12-22 21:58 UTC, KuzmaMutze commented on gulpfile.js
> +});
не вижу

2022-12-22 21:58 UTC, KuzmaMutze commented on src/sass/blocks/_description.scss
>              box-shadow: #797878;
бокс шадоу не может быть цветом

2022-12-22 21:59 UTC, KuzmaMutze commented
заливай все фиксы в один комит

2023-01-11 08:52 UTC, merged